#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue May 31 10:44:54 2022

@author: danieldavidi
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation

plt.style.use('dark_background')
fig = plt.figure()
ax = plt.axes(xlim=(-100,100),ylim=(-100,100))
line, = ax.plot([],[],lw=2)

def init():
    line.set_data([],[])
    return line,

xpoints, ypoints = [] , []

def animate(i):
    t = 0.1 * i
    x = t*np.sin(t)
    y = t*np.cos(t)
    xpoints.append(x)
    ypoints.append(y)
    line.set_data(xpoints,ypoints)
    return line,

anim = animation.FuncAnimation(fig,animate,init_func=init,frames=500,interval=50,blit=True)
anim.save('aa.htm',fps=100,writer='ffmpeg',extra_args=['-vcodec','libx264'])
